apiVersion: v1
appVersion: "3.0"
description: SiteWhere EE Kafka Ephemeral Storage
name: sitewhere-ee-kafka-ephemeral
version: 0.3.1

# Chart dependencies
dependencies:
- name: strimzi-kafka-operator
  version: 0.21.0
  repository: https://strimzi.io/charts/
  condition: strimzi.enabled
  tags:
  - infrastructure