kafka:
  name: sitewhere-kafka
  version: 2.5.0
  replicas: 3
  configuration:
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    log.message.format.version: "2.3"
zookeeper:
  replicas: 3
strimzi:
  enabled: true
  