apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sitewhere-ee.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "sitewhere-ee.name" . }}
data:
  logging.level.org.hibernate: INFO
  spring.datasource.dbname: {{ .Values.postgresql.postgresqlDatabase }}
  spring.datasource.username: {{ .Values.postgresql.postgresqlUsername }}