apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sitewhere-ee.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sitewhere-ee.name" . }}
    helm.sh/chart: {{ include "sitewhere-ee.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sitewhere-ee.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sitewhere-ee.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:9.6.5
        command: ['sh', '-c', 
          'until pg_isready -h {{ include "sitewhere-ee.fullname" . }}-postgresql-headless -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "sitewhere-ee.k8s.pod.ip"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "sitewhere-ee.namespace"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SPRING_DATASOURCE_HOSTNAME
              value: "{{ include "sitewhere-ee.fullname" . }}-postgresql-headless"
            - name: SPRING_DATASOURCE_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sitewhere-ee.fullname" . }}
                  key: spring.datasource.dbname
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sitewhere-ee.fullname" . }}
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "sitewhere-ee.fullname" . }}
                  key: postgresql-password
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}