apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sitewhere-ee.fullname" . }}
  labels:
    app: {{ template "sitewhere-ee.name" . }}
    chart: {{ template "sitewhere-ee.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-password: UGFzc3dvcmQxMjM=
  postgresql-postgres-password: UGFzc3dvcmQxMjM=
  