kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sitewhere-ee-role
  namespace: sitewhere-ee-system
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
  resourceNames: []
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["*"]
