apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-city.fullname" . }}-backend
  labels:
    {{- include "smart-city.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smart-city.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/role: backend
