apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smart-city.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "smart-city.name" . }}
data:
  logging.level.org.hibernate: INFO
  spring.datasource.dbname: {{ .Values.postgresql.postgresqlDatabase | quote }}
  sitewhere.http.protocol: {{ .Values.sitewhere.http.protocol | quote }}
  sitewhere.host: {{ .Values.sitewhere.host | quote }}
  sitewhere.port: {{ .Values.sitewhere.port | quote }}
  sitewhere.tenant.token: {{ .Values.sitewhere.tenant.token | quote }}
