{{- if .Values.ingress.enabled -}}
{{- $fullName := include "smart-city.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "smart-city.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.smartcity.host}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "smart-city.fullname" . }}-frontend
              servicePort: {{ .Values.frontend.service.port }}
          - path: /api
            backend:
              serviceName: {{ include "smart-city.fullname" . }}-backend
              servicePort: {{ .Values.backend.service.port }}
  {{- end }}
