apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci5wa2cuZ2l0aHViLmNvbSI6eyJ1c2VybmFtZSI6ImpvcmdldmlsbGF2ZXJkZS1zaXRld2hlcmUiLCJwYXNzd29yZCI6IjFlMjdkNzNmODExMmY1MGYwMTQwZmZiMmIwZDhiMTg2MjdiYjg2NWIiLCJlbWFpbCI6ImpvcmdlLnZpbGxhdmVyZGVAc2l0ZXdoZXJlLmNvbSIsImF1dGgiOiJhbTl5WjJWMmFXeHNZWFpsY21SbExYTnBkR1YzYUdWeVpUb3haVEkzWkRjelpqZ3hNVEptTlRCbU1ERTBNR1ptWWpKaU1HUTRZakU0TmpJM1ltSTROalZpIn19fQ==
kind: Secret
metadata:
  name:  {{ include "smart-city.fullname" . }}-regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-city.fullname" . }}
  labels:
    app: {{ template "smart-city.name" . }}
    chart: {{ template "smart-city.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-password: cGFzc3dvcmQ=
  postgresql-postgres-password: cGFzc3dvcmQ=
  sitewhere.user.password: cGFzc3dvcmQ=


