apiVersion: v1
appVersion: "3.0"
description: SiteWhere EE PostgreSQL
name: sitewhere-ee-postgresql
version: 0.3.0

# Chart dependencies
dependencies:
- name: postgresql
  version: 9.1.1
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
  tags:
  - infrastructure
