apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- range $name, $value := .Values.labels }}
    {{ $name }}: {{ $value }}
{{- end }}
type: {{ .Values.secret.type | default "Opaque" }}
data:
{{- range $name, $value := .Values.secret.data }}
  {{ $name }}: {{ $value }}
{{- end }}
